project_id = "model-choir-454711-c4"
github_username = "kamatnandlal"
github_repo = "kubernetes_scratch"
region     = "us-central1" 
github_manifest_path = "harness-delegate.yml"
github_branch       = "main" 
